### ISSUE TITLE
No screenshots

### ISSUE THREAD

**Issue by calda** [LumingYin/CivilizationFX#1]
Pls add screenshots / a demo video

**Comment by LumingYin** [comment]
cFX is a simple 2D JavaFX program created as a part of the CS1331 curriculum during the Fall 2016 semester. Its code is based on [CS1331 HW6](http://cs1331.gatech.edu/fall2016/hw6/hw6.html).

I have updated the project description and attached some screenshots. Thanks for the feedback, Cal! 👍
